### ISSUE TITLE
Wild Hog datasets 

### ISSUE THREAD

**Issue by Mindgames** [nextgrid/HackYeah2020#2]
Find datasets, u can look for YoloV5 data sets, but any datasets will work. The more the merrier.

- [ ] 1. Anyhogs 
- [ ] 2. Specific Hogs, Like baby hog, papa hog, etc
- [ ] 3. Images with the classification of dead hogs decide

**Comment by sandraakublik** [comment]
https://drive.google.com/drive/folders/1_2t86MNNSBCuI3Fn7pfVxOHBFFTGI4LZ

**Comment by sandraakublik** [comment]
found
